{% set name = "dagster_gcp" %}
{% set version = "0.6.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace('_', '-') }}/{{ name|replace('_', '-') }}-{{ version }}.tar.gz"
  sha256: 7a5ac2c49875bd8b4ea116de31147ac1e9d40eed6c5c946a2b4ca7e1c04818c2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster
    - dagster_pandas
    - google-api-python-client
    - google-cloud-bigquery >=1.19
    - google-cloud-storage
    - google-resumable-media
    - oauth2client

test:
  imports:
    - dagster_gcp
    - dagster_gcp.bigquery
    - dagster_gcp.dataproc
    - dagster_gcp.gcs

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-gcp"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for GCP-specific Dagster framework solid and resource components."

extra:
  recipe-maintainers:
    - conda-forge/dagster
